/*	Source File:	test.h	*/

/*
 * [BeginDoc]
 * 
 * test
 * 
 * This is the test module.  It is designed to aid in testing
 * modules by providing pseudo-random data.  Pseudo-random data is
 * valuable in the following circumstances:
 * [Verbatim]

    - When the code you are testing is designed to work as a
      container and you want to generate lots of data fairly quickly
      to test your container
    - When you are testing a sorting algorithm
    - When you want to test the limits of an algorithm by throwing
      junk at it
 * [EndDoc] */

/*
 * [BeginDoc]
 * 
 * Pseudo-random data would not necessarily be very useful if you
 * needed predictable data (c follows b which follows a).  However,
 * there are a great many types of coding problems which require
 * testing that can be tested using data generated by the test
 * module.
 * 
 * =================================================================
 * [EndDoc]
 */

#ifndef	__TEST_H__
#define	__TEST_H__

#ifdef	__cplusplus
extern "C" {
#endif

#include <sort.h>

#define	NUMBER_MOD	10
#define	CHAR_MOD	26

/*
 * Pick up documentation from test.c
 * 
 * @DocInclude ../base/test.c
 */
int testString (char *str, int len, int maxLen);
int testUpperString (char *str, int len, int maxLen);
int testMixedString (char *str, int len, int maxLen);
int testNumber (char *str, int len, int maxLen);
int testNumString (char *str, int len, int maxLen);

#ifdef	__cplusplus
}
#endif

#endif /* __TEST_H__ */
